from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Data_Analysis(object):

    def setupUi(self, Data_Analysis):
        Data_Analysis.setObjectName('Data_Analysis')
        Data_Analysis.resize(828, 605)
        self.centralwidget = QtWidgets.QWidget(Data_Analysis)
        self.centralwidget.setObjectName('centralwidget')
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 151, 31))
        self.lineEdit.setText('/home/gothe/Downloads/wall3m_2022-10-28-10-35-29.bag')
        self.lineEdit.setObjectName('lineEdit')
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName('textEdit')
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 30, 91, 31))
        self.pushButton.setObjectName('pushButton')
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 30, 101, 31))
        self.pushButton_2.setObjectName('pushButton_2')
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(90, 120, 91, 31))
        self.checkBox.setObjectName('checkBox')
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 180, 91, 31))
        self.checkBox_2.setObjectName('checkBox_2')
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(90, 210, 121, 31))
        self.checkBox_3.setObjectName('checkBox_3')
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(90, 150, 111, 31))
        self.checkBox_4.setObjectName('checkBox_4')
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 100, 131, 23))
        self.comboBox.setObjectName('comboBox')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(90, 240, 121, 31))
        self.checkBox_5.setObjectName('checkBox_5')
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(90, 350, 121, 31))
        self.checkBox_6.setObjectName('checkBox_6')
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(90, 430, 121, 31))
        self.checkBox_7.setObjectName('checkBox_7')
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(90, 390, 121, 31))
        self.checkBox_8.setObjectName('checkBox_8')
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 350, 151, 31))
        self.lineEdit_2.setText('')
        self.lineEdit_2.setObjectName('lineEdit_2')
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 390, 151, 31))
        self.lineEdit_3.setText('0,20,-0.1,0.1,0,20')
        self.lineEdit_3.setObjectName('lineEdit_3')
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 430, 151, 31))
        self.lineEdit_4.setText('')
        self.lineEdit_4.setObjectName('lineEdit_4')
        Data_Analysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Data_Analysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 20))
        self.menubar.setObjectName('menubar')
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName('menuMain')
        Data_Analysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Data_Analysis)
        self.statusbar.setObjectName('statusbar')
        Data_Analysis.setStatusBar(self.statusbar)
        self.menuMain.addSeparator()
        self.menubar.addAction(self.menuMain.menuAction())
        self.retranslateUi(Data_Analysis)
        QtCore.QMetaObject.connectSlotsByName(Data_Analysis)

    def retranslateUi(self, Data_Analysis):
        _translate = QtCore.QCoreApplication.translate
        Data_Analysis.setWindowTitle(_translate('Data_Analysis', 'Data Analysis'))
        self.textEdit.setHtml(_translate('Data_Analysis', '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;">\n<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt; font-weight:600; font-style:italic;">Open File:</span></p></body></html>'))
        self.pushButton.setText(_translate('Data_Analysis', 'Browse File'))
        self.pushButton_2.setText(_translate('Data_Analysis', 'Start Analysis'))
        self.checkBox.setText(_translate('Data_Analysis', 'FOV ROI °'))
        self.checkBox_2.setText(_translate('Data_Analysis', 'Intensity'))
        self.checkBox_3.setText(_translate('Data_Analysis', 'Point Number'))
        self.checkBox_4.setText(_translate('Data_Analysis', 'Fitting plane'))
        self.comboBox.setItemText(0, _translate('Data_Analysis', '/iv_points'))
        self.comboBox.setItemText(1, _translate('Data_Analysis', '/AT128/pandar_points'))
        self.comboBox.setItemText(2, _translate('Data_Analysis', '/rslidar_points'))
        self.checkBox_5.setText(_translate('Data_Analysis', 'POD'))
        self.checkBox_6.setText(_translate('Data_Analysis', 'Frame limit'))
        self.checkBox_7.setText(_translate('Data_Analysis', 'Intencity limit'))
        self.checkBox_8.setText(_translate('Data_Analysis', 'Bounding box'))
        self.menuMain.setTitle(_translate('Data_Analysis', 'Main'))